# Generated by Django 4.2.1 on 2023-05-24 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emplo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='designation',
            field=models.CharField(default='', max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='email',
            field=models.EmailField(max_length=40),
        ),
        migrations.AlterField(
            model_name='employee',
            name='name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.PositiveIntegerField(),
        ),
    ]
